Output uninstall.gif

Set FontSize 20
Set Width 1200
Set Height 300

Type "tpm uninstall hashicorp/aws"
Sleep 500ms
Enter
Sleep 3s

Ctrl+L
Type "tpm uninstall hashicorp/aws@latest"
Sleep 500ms
Enter
Sleep 4s

Ctrl+L
Type "tpm uninstall cloudflare/cloudflare@4.4.0"
Sleep 500ms
Enter
Sleep 3s

Ctrl+L
Type "tpm uninstall hashicorp/random --os linux,darwin --arch amd64,arm64"
Sleep 500ms
Enter
Sleep 4s
